import { Product } from "@/lib/supabase/types";

// Fallback catalogue when Supabase is unreachable. Mirror of the live
// products table — keep in sync with supabase/migrations/*.sql seeds.
// Hidden SKUs (featured=false) stay accessible by slug but never list.
//
// File-naming canon (enforced by scripts/audit-catalogue.ts):
//   <slug>-scale.webp       ← lifestyle hero (position [0] if present)
//   <slug>-pdp-white.webp   ← cyclorama hero (position [0] fallback)
//   <slug>-archive-N.webp   ← supplier raws, gallery, alts (position [2+])

const STORAGE = "https://xbtabpurfavngwmwtawc.supabase.co/storage/v1/object/public/products/drop-01";

export const STATIC_PRODUCTS: Product[] = [
  {
    id: "1",
    title: "Heritage Rucksack",
    slug: "heritage-rucksack",
    price: 32500,
    images: [
      "/assets/heritage-rucksack/heritage-rucksack.webp",
      `${STORAGE}/heritage-rucksack-scale.webp`,
      `${STORAGE}/heritage-rucksack-archive-1.webp`,
    ],
    category: "Backpack",
    status: "available",
    featured: true,
    materials: ["Full-grain Moroccan leather", "Solid brass hardware", "Hand-stitched in Marrakech"],
    dimensions: { size: "45cm × 32cm × 18cm · multi-pocket" },
    description:
      "Full-grain cognac leather rucksack with three buckled exterior pockets and a roll-top main compartment. Hand-stitched and brass-fitted by Marrakech leather artisans. Patinas with wear.",
    available_quantity: 30,
    weight_lbs: 3,
    craftsman_id: null,
    created_at: "",
    updated_at: "",
  },
  {
    id: "2",
    title: "Roll-Top Daypack",
    slug: "rolltop-daypack",
    price: 24500,
    // Original heroes (supplier-pile + souk-worn raws) failed the catalogue
    // audit. Demoted to `reserved` with no images until clean white-bg
    // PDP + scale shots land via HF. The audit skips reserved+zero-images
    // SKUs by design. Re-publish by flipping back to "available" with a
    // real images[] once -pdp-white.webp + -scale.webp arrive.
    images: [],
    category: "Backpack",
    status: "reserved",
    featured: false,
    materials: ["Full-grain Moroccan leather", "Solid brass hardware", "Hand-stitched in Marrakech"],
    dimensions: { size: "42cm × 30cm × 14cm · single-pocket" },
    description:
      "Cleaner cousin to the Heritage Rucksack. Single front pocket, X-strap closure, soft Moroccan tan leather that softens into the body with use. Built for daily carry.",
    available_quantity: 30,
    weight_lbs: 2.5,
    craftsman_id: null,
    created_at: "",
    updated_at: "",
  },
  {
    id: "3",
    title: "Black Stitched Backpack",
    slug: "black-stitched-backpack",
    price: 24500,
    images: [
      `${STORAGE}/black-stitched-backpack-pdp-white.webp`,
      `${STORAGE}/black-stitched-backpack-archive-1.webp`,
      `${STORAGE}/black-stitched-backpack-archive-2.webp`,
      `${STORAGE}/black-stitched-backpack-archive-3.webp`,
      `${STORAGE}/black-stitched-backpack-archive-4.webp`,
    ],
    category: "Backpack",
    status: "available",
    featured: true,
    materials: ["Full-grain Moroccan leather", "Cream contrast zigzag stitching", "Solid brass buckle", "Tan-finished interior", "Hand-stitched in Marrakech"],
    dimensions: { size: "40cm × 28cm × 12cm · single-buckle flap" },
    description:
      "Boxy square-cut backpack in deep black full-grain leather, framed by a cream zigzag stitch border. Single brass buckle closure, internal zip pocket, dual adjustable shoulder straps. Editorial silhouette, daily-carry size.",
    available_quantity: 20,
    weight_lbs: 2.5,
    craftsman_id: null,
    created_at: "",
    updated_at: "",
  },
  {
    id: "4",
    title: "Cognac Brogue Backpack",
    slug: "cognac-brogue-backpack",
    price: 26500,
    images: [
      `${STORAGE}/cognac-brogue-backpack-pdp-white.webp`,
      `${STORAGE}/cognac-brogue-backpack-archive-1.webp`,
      `${STORAGE}/cognac-brogue-backpack-archive-2.webp`,
    ],
    category: "Backpack",
    status: "available",
    featured: true,
    materials: ["Full-grain Moroccan leather", "Brogue-style edge stitching", "Brass buckle hardware", "Hand-stitched in Marrakech"],
    dimensions: { size: "38cm × 30cm × 12cm · single front pocket" },
    description:
      "Cognac full-grain backpack with brogue-style scallop stitching framing each panel. Long flap with single buckle, external front pocket, leather top handle plus adjustable shoulder straps. Patinas warm with wear.",
    available_quantity: 20,
    weight_lbs: 2.5,
    craftsman_id: null,
    created_at: "",
    updated_at: "",
  },
  {
    id: "5",
    title: "Classic Cognac Satchel",
    slug: "classic-cognac-satchel",
    price: 28500,
    images: [
      `${STORAGE}/classic-cognac-satchel-pdp-white.webp`,
      `${STORAGE}/classic-cognac-satchel-archive-1.webp`,
      `${STORAGE}/classic-cognac-satchel-archive-2.webp`,
      `${STORAGE}/classic-cognac-satchel-archive-3.webp`,
    ],
    category: "Satchel",
    status: "available",
    featured: true,
    materials: ["Full-grain Moroccan leather", "Dual brass buckle closures", "Top carry handle + crossbody strap", "Cream contrast saddle-stitch", "Hand-stitched in Marrakech"],
    dimensions: { size: "40cm × 30cm × 12cm · briefcase silhouette" },
    description:
      "Classic briefcase satchel in rich cognac full-grain leather. Dual brass buckle closures, sturdy top handle plus removable crossbody strap. Cream saddle-stitch edges throughout. Carries a 14\" laptop. Heirloom-grade.",
    available_quantity: 20,
    weight_lbs: 3,
    craftsman_id: null,
    created_at: "",
    updated_at: "",
  },
  {
    id: "6",
    title: "Woven Leather Backpack",
    slug: "woven-leather-backpack",
    price: 29500,
    images: [
      `${STORAGE}/woven-leather-backpack-pdp-white.webp`,
      `${STORAGE}/woven-leather-backpack-archive-1.webp`,
    ],
    category: "Backpack",
    status: "available",
    featured: true,
    materials: ["Full-grain Moroccan leather", "Hand-woven leather panels", "Brass-finished buckle", "Drawstring closure", "Hand-stitched in Marrakech"],
    dimensions: { size: "36cm × 28cm · drawstring + flap" },
    description:
      "Dark-chocolate full-grain leather woven by hand into a diamond lattice across the body and flap. Drawstring inner closure under the buckled flap. Smooth saddle leather base and shoulder straps. The most labour-intensive bag in the drop.",
    available_quantity: 15,
    weight_lbs: 2.5,
    craftsman_id: null,
    created_at: "",
    updated_at: "",
  },
  {
    id: "7",
    title: "Vintage Buckle Backpack",
    slug: "vintage-buckle-backpack",
    price: 22500,
    images: [
      `${STORAGE}/vintage-buckle-backpack-pdp-white.webp`,
      `${STORAGE}/vintage-buckle-backpack-archive-1.webp`,
    ],
    category: "Backpack",
    status: "available",
    featured: true,
    materials: ["Full-grain Moroccan leather", "Aged brass hardware", "Three external pockets", "Drawstring inner closure", "Hand-stitched in Marrakech"],
    dimensions: { size: "38cm × 30cm × 14cm · drawstring + 3 pockets" },
    description:
      "Safari-classic silhouette in cognac full-grain leather. Buckled flap over a drawstring inner closure, plus three exterior buckled pockets (one front, two side). Patinas to a deep tobacco with daily wear.",
    available_quantity: 25,
    weight_lbs: 2.5,
    craftsman_id: null,
    created_at: "",
    updated_at: "",
  },
  {
    id: "8",
    title: "Atlas Kilim Duffle",
    slug: "atlas-kilim-duffle",
    price: 44500,
    images: [
      "/assets/atlas-kilim-duffle/atlas-kilim-duffle.webp",
    ],
    category: "Weekender",
    status: "available",
    featured: true,
    materials: [
      "Full-grain Moroccan leather",
      "Handwoven kilim wool panels (Atlas Mountains)",
      "Solid antique brass middle strap buckle",
      "Hand saddle-stitched in Marrakech",
    ],
    dimensions: { size: "50cm × 28cm × 26cm · weekender with kilim panel inserts" },
    description:
      "Travel weekender in saddle cognac leather framing handwoven kilim wool panels sourced from Atlas weavers. Brass middle strap, dual rolled handles. The signature Morocco-meets-luxury anchor of the maison.",
    available_quantity: 12,
    weight_lbs: 3.5,
    craftsman_id: null,
    created_at: "",
    updated_at: "",
  },
  {
    id: "9",
    title: "Explorer Rolltop · Cognac",
    slug: "explorer-rolltop-cognac",
    price: 28500,
    images: [
      "/assets/explorer-rolltop-cognac/explorer-rolltop-cognac.webp",
    ],
    category: "Backpack",
    status: "available",
    featured: true,
    materials: [
      "Full-grain Moroccan leather",
      "Solid antique brass center buckle",
      "Brass YKK zip front panel",
      "Adjustable dual shoulder straps",
      "Hand saddle-stitched in Marrakech",
    ],
    dimensions: { size: "44cm × 30cm × 16cm · rolltop with brass center buckle" },
    description:
      "Modern rolltop rucksack in deep saddle cognac. Brass center buckle closes a full-bleed roll-down panel; a brass zip pocket runs the vertical centerline. Patinas warm and softens at the corners with daily carry.",
    available_quantity: 18,
    weight_lbs: 2.5,
    craftsman_id: null,
    created_at: "",
    updated_at: "",
  },
  {
    id: "10",
    title: "Medina Envelope Crossbody",
    slug: "medina-crossbody-envelope",
    price: 18500,
    images: [
      "/assets/medina-crossbody-envelope/medina-crossbody-envelope.webp",
    ],
    category: "Crossbody",
    status: "available",
    featured: true,
    materials: [
      "Full-grain Moroccan leather",
      "Solid antique brass turn-lock",
      "Adjustable shoulder strap",
      "Hand saddle-stitched in Marrakech",
    ],
    dimensions: { size: "24cm × 18cm × 4cm · envelope flap" },
    description:
      "Compact envelope crossbody in deep walnut leather, finished with a single brass turn-lock and an adjustable saddle strap. Quiet enough for evening, structured enough for daily carry.",
    available_quantity: 25,
    weight_lbs: 0.7,
    craftsman_id: null,
    created_at: "",
    updated_at: "",
  },
  {
    id: "11",
    title: "Medina Drawstring Rucksack",
    slug: "medina-rucksack-drawstring",
    price: 25500,
    images: [
      "/assets/medina-rucksack-drawstring/medina-rucksack-drawstring.webp",
    ],
    category: "Backpack",
    status: "available",
    featured: true,
    materials: [
      "Full-grain Moroccan leather",
      "Solid antique brass front buckle",
      "Drawstring closure",
      "Adjustable single shoulder strap",
      "Hand saddle-stitched in Marrakech",
    ],
    dimensions: { size: "tall duffle silhouette · single shoulder strap" },
    description:
      "Tall cognac drawstring rucksack with a single front buckled pocket and adjustable shoulder strap. A sailor's silhouette translated to luxury full-grain Moroccan leather. Patinas richer with each season.",
    available_quantity: 20,
    weight_lbs: 2,
    craftsman_id: null,
    created_at: "",
    updated_at: "",
  },
  // ─── Drop 02 expansion (Maison Tanneurs naming — Moroccan with French flavor) ───
  {
    id: "12",
    title: "Saharienne Saddle · Cognac",
    slug: "saharienne-saddle-cognac",
    price: 24500,
    images: [
      "/products/saharienne-saddle-cognac/saharienne-saddle-cognac-pdp-white.webp",
      "/products/saharienne-saddle-cognac/saharienne-saddle-cognac-archive-1.webp",
      "/products/saharienne-saddle-cognac/saharienne-saddle-cognac-archive-2.webp",
      "/products/saharienne-saddle-cognac/saharienne-saddle-cognac-archive-3.webp",
      "/products/saharienne-saddle-cognac/saharienne-saddle-cognac-archive-4.webp",
      "/products/saharienne-saddle-cognac/saharienne-saddle-cognac-archive-5.webp",
      "/products/saharienne-saddle-cognac/saharienne-saddle-cognac-archive-6.webp",
      "/products/saharienne-saddle-cognac/saharienne-saddle-cognac-archive-7.webp",
      "/products/saharienne-saddle-cognac/saharienne-saddle-cognac-archive-8.webp",
    ],
    category: "Crossbody",
    status: "available",
    featured: true,
    materials: [
      "Full-grain Moroccan leather",
      "Solid brass push-lock catch",
      "Structured saddle silhouette",
      "Hand saddle-stitched in Marrakech",
    ],
    dimensions: { size: "22cm × 18cm × 10cm · single flap closure" },
    description:
      "Small structured saddle bag in cognac full-grain leather, finished with a single brass push-lock catch and clean centerline seam. Day-to-evening crossbody scale. Patinas warm with wear.",
    available_quantity: 18,
    weight_lbs: 1.2,
    craftsman_id: null,
    created_at: "",
    updated_at: "",
  },
  {
    id: "13",
    title: "Médersa Rucksack · Cognac",
    slug: "medersa-rucksack-cognac",
    price: 32500,
    images: [
      "/products/medersa-rucksack-cognac/medersa-rucksack-cognac-pdp-white.webp",
      "/products/medersa-rucksack-cognac/medersa-rucksack-cognac-archive-1.webp",
      "/products/medersa-rucksack-cognac/medersa-rucksack-cognac-archive-2.webp",
      "/products/medersa-rucksack-cognac/medersa-rucksack-cognac-archive-3.webp",
      "/products/medersa-rucksack-cognac/medersa-rucksack-cognac-archive-4.webp",
      "/products/medersa-rucksack-cognac/medersa-rucksack-cognac-archive-5.webp",
      "/products/medersa-rucksack-cognac/medersa-rucksack-cognac-archive-6.webp",
      "/products/medersa-rucksack-cognac/medersa-rucksack-cognac-archive-7.webp",
      "/products/medersa-rucksack-cognac/medersa-rucksack-cognac-archive-8.webp",
    ],
    category: "Backpack",
    status: "available",
    featured: true,
    materials: [
      "Full-grain Moroccan leather",
      "Solid brass YKK zippers (×4)",
      "Leather tassel zipper pulls",
      "Padded laptop sleeve interior",
      "Hand saddle-stitched in Marrakech",
    ],
    dimensions: { size: "42cm × 30cm × 16cm · multi-compartment utility" },
    description:
      "Travel-grade utility rucksack in cognac full-grain leather. Four brass zippers with leather tassel pulls open onto a padded main, a top-zip dopp compartment, and a side flap pocket. Built for long carry days, softens with wear.",
    available_quantity: 14,
    weight_lbs: 3.2,
    craftsman_id: null,
    created_at: "",
    updated_at: "",
  },
  {
    id: "14",
    title: "Babouche Crossbody · Cognac",
    slug: "babouche-crossbody-cognac",
    price: 18500,
    images: [
      "/products/babouche-crossbody-cognac/babouche-crossbody-cognac-pdp-white.webp",
      "/products/babouche-crossbody-cognac/babouche-crossbody-cognac-archive-1.webp",
      "/products/babouche-crossbody-cognac/babouche-crossbody-cognac-archive-2.webp",
      "/products/babouche-crossbody-cognac/babouche-crossbody-cognac-archive-3.webp",
      "/products/babouche-crossbody-cognac/babouche-crossbody-cognac-archive-4.webp",
      "/products/babouche-crossbody-cognac/babouche-crossbody-cognac-archive-5.webp",
      "/products/babouche-crossbody-cognac/babouche-crossbody-cognac-archive-6.webp",
      "/products/babouche-crossbody-cognac/babouche-crossbody-cognac-archive-7.webp",
      "/products/babouche-crossbody-cognac/babouche-crossbody-cognac-archive-8.webp",
    ],
    category: "Crossbody",
    status: "available",
    featured: true,
    materials: [
      "Pebbled-grain Moroccan leather",
      "Solid brass twin-stud closure",
      "Adjustable shoulder strap",
      "Hand saddle-stitched in Marrakech",
    ],
    dimensions: { size: "20cm × 16cm × 7cm · soft crossbody" },
    description:
      "Soft pebbled-grain crossbody in cognac, with a quiet twin-stud brass closure. Day daily-carry scale — phone, wallet, keys. The smallest piece in the maison, the most personal.",
    available_quantity: 24,
    weight_lbs: 0.9,
    craftsman_id: null,
    created_at: "",
    updated_at: "",
  },
  {
    id: "15",
    title: "Kilim Duffle · Polychrome",
    slug: "kilim-duffle-polychrome",
    price: 46500,
    images: [
      "/products/kilim-duffle-polychrome/kilim-duffle-polychrome-pdp-white.webp",
      "/products/kilim-duffle-polychrome/kilim-duffle-polychrome-archive-1.webp",
      "/products/kilim-duffle-polychrome/kilim-duffle-polychrome-archive-2.webp",
      "/products/kilim-duffle-polychrome/kilim-duffle-polychrome-archive-3.webp",
      "/products/kilim-duffle-polychrome/kilim-duffle-polychrome-archive-4.webp",
      "/products/kilim-duffle-polychrome/kilim-duffle-polychrome-archive-5.webp",
      "/products/kilim-duffle-polychrome/kilim-duffle-polychrome-archive-6.webp",
      "/products/kilim-duffle-polychrome/kilim-duffle-polychrome-archive-7.webp",
      "/products/kilim-duffle-polychrome/kilim-duffle-polychrome-archive-8.webp",
    ],
    category: "Weekender",
    status: "available",
    featured: true,
    materials: [
      "Full-grain cognac leather frame",
      "Handwoven polychrome kilim wool panels",
      "Solid brass end fittings",
      "Dual rolled leather handles",
      "Hand saddle-stitched in Marrakech",
    ],
    dimensions: { size: "48cm × 26cm × 24cm · barrel duffle" },
    description:
      "Statement barrel duffle in cognac leather framing handwoven polychrome kilim panels — red, green, ochre and cream stripes with woven diamond accents. Every piece is unique to its panel. The kilim register of the maison.",
    available_quantity: 8,
    weight_lbs: 3.4,
    craftsman_id: null,
    created_at: "",
    updated_at: "",
  },
  {
    id: "16",
    title: "Kilim Duffle · Amber",
    slug: "kilim-duffle-amber",
    price: 46500,
    images: [
      "/products/kilim-duffle-amber/kilim-duffle-amber-pdp-white.webp",
      "/products/kilim-duffle-amber/kilim-duffle-amber-archive-1.webp",
      "/products/kilim-duffle-amber/kilim-duffle-amber-archive-2.webp",
      "/products/kilim-duffle-amber/kilim-duffle-amber-archive-3.webp",
      "/products/kilim-duffle-amber/kilim-duffle-amber-archive-4.webp",
      "/products/kilim-duffle-amber/kilim-duffle-amber-archive-5.webp",
      "/products/kilim-duffle-amber/kilim-duffle-amber-archive-6.webp",
      "/products/kilim-duffle-amber/kilim-duffle-amber-archive-7.webp",
      "/products/kilim-duffle-amber/kilim-duffle-amber-archive-8.webp",
    ],
    category: "Weekender",
    status: "available",
    featured: true,
    materials: [
      "Full-grain cognac leather frame",
      "Handwoven amber kilim wool panels",
      "Solid brass end fittings",
      "Dual rolled leather handles",
      "Hand saddle-stitched in Marrakech",
    ],
    dimensions: { size: "48cm × 26cm × 24cm · barrel duffle" },
    description:
      "Sister piece to the Polychrome — same barrel duffle silhouette with handwoven kilim panels in an amber palette: orange, terracotta, cream and chocolate diamond motifs. Berber geometric tradition, French maison register.",
    available_quantity: 8,
    weight_lbs: 3.4,
    craftsman_id: null,
    created_at: "",
    updated_at: "",
  },
  {
    id: "17",
    title: "Cèdre Crossbody · Chocolate",
    slug: "cedre-crossbody-chocolate",
    price: 21500,
    images: [
      "/products/cedre-crossbody-chocolate/cedre-crossbody-chocolate-pdp-white.webp",
      "/products/cedre-crossbody-chocolate/cedre-crossbody-chocolate-archive-1.webp",
      "/products/cedre-crossbody-chocolate/cedre-crossbody-chocolate-archive-2.webp",
      "/products/cedre-crossbody-chocolate/cedre-crossbody-chocolate-archive-3.webp",
      "/products/cedre-crossbody-chocolate/cedre-crossbody-chocolate-archive-4.webp",
      "/products/cedre-crossbody-chocolate/cedre-crossbody-chocolate-archive-5.webp",
      "/products/cedre-crossbody-chocolate/cedre-crossbody-chocolate-archive-6.webp",
      "/products/cedre-crossbody-chocolate/cedre-crossbody-chocolate-archive-7.webp",
      "/products/cedre-crossbody-chocolate/cedre-crossbody-chocolate-archive-8.webp",
    ],
    category: "Crossbody",
    status: "available",
    featured: true,
    materials: [
      "Distressed-finish chocolate Moroccan leather",
      "Solid brass push-lock catch",
      "Cream contrast saddle-stitching",
      "Adjustable shoulder strap",
      "Hand saddle-stitched in Marrakech",
    ],
    dimensions: { size: "26cm × 22cm × 8cm · flap crossbody" },
    description:
      "Medium-weight crossbody in deep chocolate distressed leather with cream contrast saddle-stitch and a brass push-lock. The most worn-in colorway in the drop. Cedar-wood tonality.",
    available_quantity: 16,
    weight_lbs: 1.3,
    craftsman_id: null,
    created_at: "",
    updated_at: "",
  },
  {
    id: "18",
    title: "Tadelakt Rucksack · Cognac",
    slug: "tadelakt-rucksack-cognac",
    price: 29500,
    images: [
      "/products/tadelakt-rucksack-cognac/tadelakt-rucksack-cognac-pdp-white.webp",
      "/products/tadelakt-rucksack-cognac/tadelakt-rucksack-cognac-archive-1.webp",
      "/products/tadelakt-rucksack-cognac/tadelakt-rucksack-cognac-archive-2.webp",
      "/products/tadelakt-rucksack-cognac/tadelakt-rucksack-cognac-archive-3.webp",
      "/products/tadelakt-rucksack-cognac/tadelakt-rucksack-cognac-archive-4.webp",
      "/products/tadelakt-rucksack-cognac/tadelakt-rucksack-cognac-archive-5.webp",
      "/products/tadelakt-rucksack-cognac/tadelakt-rucksack-cognac-archive-6.webp",
      "/products/tadelakt-rucksack-cognac/tadelakt-rucksack-cognac-archive-7.webp",
      "/products/tadelakt-rucksack-cognac/tadelakt-rucksack-cognac-archive-8.webp",
    ],
    category: "Backpack",
    status: "available",
    featured: true,
    materials: [
      "Full-grain Moroccan leather",
      "Solid brass front zipper",
      "Leather tassel pull",
      "Cream contrast saddle-stitching",
      "Hand saddle-stitched in Marrakech",
    ],
    dimensions: { size: "38cm × 32cm × 14cm · vertical-zip rucksack" },
    description:
      "Refined commuter rucksack in cognac full-grain leather with a vertical brass front zipper, leather tassel pull, and cream saddle-stitched edge. Tadelakt-smooth surface, finished by hand.",
    available_quantity: 14,
    weight_lbs: 2.4,
    craftsman_id: null,
    created_at: "",
    updated_at: "",
  },
  {
    id: "19",
    title: "Safran Tote · Cognac",
    slug: "safran-tote-cognac",
    price: 24500,
    images: [
      "/products/safran-tote-cognac/safran-tote-cognac-pdp-white.webp",
      "/products/safran-tote-cognac/safran-tote-cognac-archive-1.webp",
      "/products/safran-tote-cognac/safran-tote-cognac-archive-2.webp",
      "/products/safran-tote-cognac/safran-tote-cognac-archive-3.webp",
      "/products/safran-tote-cognac/safran-tote-cognac-archive-4.webp",
      "/products/safran-tote-cognac/safran-tote-cognac-archive-5.webp",
      "/products/safran-tote-cognac/safran-tote-cognac-archive-6.webp",
      "/products/safran-tote-cognac/safran-tote-cognac-archive-7.webp",
      "/products/safran-tote-cognac/safran-tote-cognac-archive-8.webp",
    ],
    category: "Tote",
    status: "available",
    featured: true,
    materials: [
      "Full-grain Moroccan leather",
      "Dual parallel rolled handles",
      "Center spine seam (front + back)",
      "Hand saddle-stitched in Marrakech",
    ],
    dimensions: { size: "38cm × 32cm × 12cm · east-west tote" },
    description:
      "East-west day tote in saffron-warm cognac leather. Two parallel rolled handles, a single center spine seam, open top. Carries a 13\" laptop and a slim book. Softens into the body over months of carry.",
    available_quantity: 20,
    weight_lbs: 1.8,
    craftsman_id: null,
    created_at: "",
    updated_at: "",
  },
  {
    id: "20",
    title: "Rif Heritage Rucksack · Tan",
    slug: "rif-rucksack-tan",
    price: 28500,
    images: [
      "/products/rif-rucksack-tan/rif-rucksack-tan-pdp-white.webp",
      "/products/rif-rucksack-tan/rif-rucksack-tan-archive-1.webp",
      "/products/rif-rucksack-tan/rif-rucksack-tan-archive-2.webp",
      "/products/rif-rucksack-tan/rif-rucksack-tan-archive-3.webp",
      "/products/rif-rucksack-tan/rif-rucksack-tan-archive-4.webp",
      "/products/rif-rucksack-tan/rif-rucksack-tan-archive-5.webp",
      "/products/rif-rucksack-tan/rif-rucksack-tan-archive-6.webp",
      "/products/rif-rucksack-tan/rif-rucksack-tan-archive-7.webp",
      "/products/rif-rucksack-tan/rif-rucksack-tan-archive-8.webp",
    ],
    category: "Backpack",
    status: "available",
    featured: true,
    materials: [
      "Full-grain tan Moroccan leather",
      "Twin front buckled pockets",
      "Drawstring closure under flap",
      "Cream contrast saddle-stitch",
      "Hand saddle-stitched in Marrakech",
    ],
    dimensions: { size: "40cm × 32cm × 16cm · classic flap rucksack" },
    description:
      "Heritage classic rucksack in soft tan full-grain leather. Twin buckled front pockets, drawstring inner closure under a flap, cream contrast saddle-stitch throughout. Built like field gear, finished like maison goods.",
    available_quantity: 16,
    weight_lbs: 2.8,
    craftsman_id: null,
    created_at: "",
    updated_at: "",
  },
];

// Merge a Supabase product list with STATIC_PRODUCTS:
//   1. For each Supabase row whose slug also exists in STATIC, overlay STATIC's
//      category if Supabase's is the legacy "Leather Goods" value. Keeps
//      Supabase's descriptions / prices / images but fixes category routing
//      before the recategorize SQL migration is applied.
//   2. Append any STATIC entry whose slug isn't in Supabase at all (Drop 02).
// Drops STATIC entries that aren't available.
export function mergeWithStatic(supabaseProducts: Product[]): Product[] {
  const staticBySlug = new Map(STATIC_PRODUCTS.map((p) => [p.slug, p]));
  const overlaid = supabaseProducts.map((p) => {
    const s = staticBySlug.get(p.slug);
    if (s && p.category === "Leather Goods" && s.category !== "Leather Goods") {
      return { ...p, category: s.category };
    }
    return p;
  });
  const seen = new Set(supabaseProducts.map((p) => p.slug));
  const supplement = STATIC_PRODUCTS.filter(
    (p) => !seen.has(p.slug) && p.status === "available",
  );
  return [...overlaid, ...supplement];
}

export const CATEGORIES = ["All", "Backpack", "Crossbody", "Tote", "Weekender", "Satchel"] as const;

export type Category = (typeof CATEGORIES)[number];

export const LIGHTING_DB_CATEGORIES = [] as const;
